# .github/workflows/nuget-publish.yml
# Simple workflow to publish FunctionalKit to NuGet

name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack ./FunctionalKit/FunctionalKit.csproj --configuration Release --no-build --output ./packages

      - name: Publish to NuGet
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: FunctionalKit ${{ github.ref_name }}
          body: |
            ## FunctionalKit ${{ github.ref_name }}
            
            Install this version:
            ```bash
            dotnet add package FunctionalKit --version ${{ github.ref_name }}
            ```
            
            [View on NuGet](https://www.nuget.org/packages/FunctionalKit/${{ github.ref_name }})
          draft: false
          prerelease: false